.PHONY: clean All

All:
	@echo "----------Building project:[ Programmation - Debug ]----------"
	@"$(MAKE)" -f  "Programmation.mk"
clean:
	@echo "----------Cleaning project:[ Programmation - Debug ]----------"
	@"$(MAKE)" -f  "Programmation.mk" clean
